name: Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    container:
      image: 'ghcr.io/void-linux/void-mklive:20250116R1'
      options: --privileged

    steps:
      - name: Fix SSL and install tools
        run: |
          xbps-install -Syu --repository=https://repo-de.voidlinux.org/current/ xbps
          xbps-install -Suyd --repository=https://repo-de.voidlinux.org/current/
          xbps-install -y --repository=https://repo-de.voidlinux.org/current/ wget nodejs ca-certificates ntp git base-devel xtools sudo rsync openssh sshpass python3 python3-pip tar
          
          python3 -m pip install -U "huggingface_hub[cli]" --break-system-packages
          
          groupadd -f xbuilder
          useradd -m -s /bin/bash -G xbuilder builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Copy template
        run: |
          git clone --depth 1 https://github.com/javiercplus/void-packages.git /tmp/void-packages
          cd /tmp/void-packages
          
          git clone --depth 1 https://github.com/javiercplus/falcond-wd.git srcpkgs/falcond-wd

          echo "#nnothing" >> common/build-style/none.sh
          chown -R builder:builder /tmp/void-packages

      - name: Build package
        run: |
          su - builder -c "cd /tmp/void-packages && ./xbps-src binary-bootstrap"
          su - builder -c "cd /tmp/void-packages && ./xbps-src fetch falcond-wd"
          su - builder -c "cd /tmp/void-packages && ./xbps-src pkg falcond-wd"
          

      - name: Sign packages and index
        run: |
          echo "${{ secrets.XBPS_PRIVATE_KEY }}" > /tmp/privkey.pem
          cd /tmp/void-packages/hostdir/binpkgs
          
          xbps-rindex --sign-pkg --privkey /tmp/privkey.pem *.xbps
          xbps-rindex -a *.xbps
          xbps-rindex --sign --signedby "javierc" --privkey /tmp/privkey.pem .
          
          rm /tmp/privkey.pem
    
      - name: Compress and upload to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd /tmp/void-packages/hostdir/binpkgs
          VERSION=$(date +"%Y%m%d")
          tar -czvf /tmp/neko-packages.tar.gz .
          
          hf upload arepaconcafe/repo /tmp/neko-packages.tar.gz test-$VERSION.tar.gz --repo-type dataset --token $HF_TOKEN
